name: cli
description: A sample command-line application.
version: 0.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  file_picker_desktop: ^1.1.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
