name: Dart Release Build

on:
  push:
    tags:
      - 'v*'  # z.B. v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Get dependencies
      run: dart pub get

    - name: Build binary
      run: |
        mkdir -p build
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          dart compile exe bin/cli.dart -o build/my_dart_cli-linux
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          dart compile exe bin/cli.dart -o build/my_dart_cli-macos
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          dart compile exe bin/cli.dart -o build/my_dart_cli.exe
        fi
      shell: bash

    - name: Upload artifact for later release step
      uses: actions/upload-artifact@v4
      with:
        name: my_dart_cli-${{ runner.os }}
        path: build/*
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: build/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
